# Generated by Django 2.0.2 on 2018-02-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0002_auto_20180215_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_img_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
